apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksTaskAK
  region: ap-south-1

nodeGroups:
- name: nodegroup1
  desiredCapacity: 1
  instanceType: t2.micro
  ssh:
    publicKeyName: eks_key_pair

- name: nodegroup2
  desiredCapacity: 1
  instanceType: t2.micro
  ssh:
    publicKeyName: eks_key_pair

- name: mixednodegroup
  minSize: 2
  maxSize: 5
  instancesDistribution:
    maxPrice: 0.015
    instanceTypes: ["t3.small" , "t3.medium"]
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 65
    spotInstancePools: 2
  ssh:
    publicKeyName: eks_key_pair